# generated by chat

from dataclasses import dataclass
from typing import Optional

import geopandas as gpd
import pandas as pd
import numpy as np

import folium
from folium import FeatureGroup
from folium.plugins import MarkerCluster
import branca.colormap as cm


def _ensure_edge_id(edges: gpd.GeoDataFrame) -> gpd.GeoDataFrame:
    if "edge_id" in edges.columns:
        return edges
    if not all(c in edges.columns for c in ("u", "v", "key")):
        raise ValueError("Edges must have edge_id or u/v/key columns.")
    edges = edges.copy()
    edges["edge_id"] = edges.apply(lambda r: f"{int(r['u'])}_{int(r['v'])}_{int(r['key'])}", axis=1)
    return edges


def _center_latlon(gdf_4326: gpd.GeoDataFrame) -> tuple[float, float]:
    if gdf_4326.empty:
        return (37.2296, -80.4139)  # Blacksburg fallback
    c = gdf_4326.geometry.unary_union.centroid
    return (float(c.y), float(c.x))


def render_risk_map(
    *,
    osm_edges_path: str,
    crashes_path: str,
    predictions_path: str,
    out_html_path: str,
    # Column names:
    pred_key: str = "edge_id",
    pred_value: str = "rate_pred",
    # Visual tuning:
    show_raw_roads: bool = True,
    show_risk_roads: bool = True,
    show_crashes: bool = True,
    crash_marker_cluster: bool = True,
    risk_quantile_clip: float = 0.99,
) -> None:
    """
    Creates a toggleable interactive map:
      - Raw roads (gray)
      - Risk-colored roads (by rate_pred)
      - Crash points
    """
    # Load data
    edges = gpd.read_parquet(osm_edges_path)
    edges = _ensure_edge_id(edges)

    crashes = gpd.read_parquet(crashes_path)
    preds = pd.read_parquet(predictions_path)

    # Reproject to WGS84 for web map
    if edges.crs is None:
        raise ValueError("OSM edges have no CRS. They must be projected and saved with CRS.")
    edges_4326 = edges.to_crs("EPSG:4326")

    if crashes.crs is None:
        raise ValueError("Crashes GeoDataFrame has no CRS. It must be saved with CRS.")
    crashes_4326 = crashes.to_crs("EPSG:4326")

    # Join predictions onto edges
    if pred_key not in preds.columns:
        raise ValueError(f"Predictions must contain '{pred_key}' column.")
    if pred_value not in preds.columns:
        raise ValueError(f"Predictions must contain '{pred_value}' column.")

    edges_pred = edges_4326.merge(preds[[pred_key, pred_value]], on=pred_key, how="left")

    # Clean risk values and define color scale
    risk = edges_pred[pred_value].astype(float)
    # Replace NaN with 0 for display
    risk = risk.fillna(0.0)

    # Clip extreme values for visualization (prevents 1 edge dominating colors)
    clip_val = float(risk.quantile(risk_quantile_clip)) if len(risk) else 1.0
    clip_val = max(clip_val, 1e-12)
    risk_clip = np.clip(risk.to_numpy(), 0.0, clip_val)
    edges_pred["_risk_clip"] = risk_clip

    # Logarithmic color scaling to improve low-end contrast.
    risk_color = np.log1p(risk_clip)
    color_max = float(np.log1p(clip_val))
    edges_pred["_risk_color"] = risk_color

    # Colormap (simple; adjust later if desired)
    colormap = cm.linear.YlOrRd_09.scale(0.0, max(color_max, 1e-12))
    colormap.caption = (
        f"Predicted risk (rate_pred), log-scaled (log1p), clipped at q={risk_quantile_clip}"
    )

    # Create map
    center = _center_latlon(edges_4326)
    m = folium.Map(location=center, zoom_start=13, control_scale=True, tiles="CartoDB positron")

    # --- Layer: raw roads (gray)
    if show_raw_roads:
        fg_roads = FeatureGroup(name="Road geometry (raw)", show=True)

        folium.GeoJson(
            edges_4326[["edge_id", "geometry"]],
            name="raw_roads",
            style_function=lambda feature: {
                "color": "#666666",
                "weight": 2,
                "opacity": 0.5,
            },
            tooltip=folium.GeoJsonTooltip(fields=["edge_id"]),
        ).add_to(fg_roads)

        fg_roads.add_to(m)

    # --- Layer: risk roads (colored)
    if show_risk_roads:
        fg_risk = FeatureGroup(name="Risk layer (rate_pred)", show=True)

        def style_risk(feature):
            v = feature["properties"].get("_risk_color", 0.0)
            return {
                "color": colormap(v),
                "weight": 4,
                "opacity": 0.85,
            }

        folium.GeoJson(
            edges_pred[["edge_id", "_risk_clip", "_risk_color", pred_value, "geometry"]],
            name="risk_roads",
            style_function=style_risk,
            tooltip=folium.GeoJsonTooltip(fields=["edge_id", pred_value]),
        ).add_to(fg_risk)

        fg_risk.add_to(m)
        colormap.add_to(m)

    # --- Layer: crashes (points)
    if show_crashes:
        fg_crashes = FeatureGroup(name="Crash locations (raw)", show=False)

        # Keep only points
        crash_pts = crashes_4326[crashes_4326.geometry.type == "Point"].copy()

        if crash_marker_cluster:
            cluster = MarkerCluster(name="Crash cluster")
            for _, row in crash_pts.iterrows():
                p = row.geometry
                folium.CircleMarker(
                    location=(p.y, p.x),
                    radius=3,
                    fill=True,
                    fill_opacity=0.6,
                    opacity=0.6,
                ).add_to(cluster)
            cluster.add_to(fg_crashes)
        else:
            for _, row in crash_pts.iterrows():
                p = row.geometry
                folium.CircleMarker(
                    location=(p.y, p.x),
                    radius=3,
                    fill=True,
                    fill_opacity=0.6,
                    opacity=0.6,
                ).add_to(fg_crashes)

        fg_crashes.add_to(m)

    folium.LayerControl(collapsed=False).add_to(m)

    # Save
    import os
    os.makedirs(os.path.dirname(out_html_path), exist_ok=True)
    m.save(out_html_path)
